name: Manual PR CI

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1：通过 GitHub API 获取 PR 详细信息（使用正确语法）
      - name: Fetch PR Details
        id: fetch-pr
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr_number }},
            });
            // 将结果直接写入步骤输出
            core.setOutput('sha', pr.data.head.sha);
            core.setOutput('branch', pr.data.head.ref);

      # 步骤 2：使用步骤输出中的 SHA 检出代码
      - name: Checkout PR Code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.fetch-pr.outputs.sha }}

      # 后续步骤保持不变
      - name: Setup environment
        run: echo "Setting up environment"
      
      - name: Build
        run: echo "Building project"
      
      - name: Run tests
        run: echo "Running tests"
