name: Auto PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Setup environment
        run: |
          npm install -g pnpm
          pnpm install

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test
