name: Manual CI Workflow

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Number to run CI on'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.inputs.pr_number }}/merge
          
      # 这里添加你的CI步骤
      - name: Setup environment
        run: echo "Setting up environment"
        
      - name: Build
        run: echo "Building project"
        
      - name: Run tests
        run: echo "Running tests"
