name: Auto PR CI

on:
  # PR 触发事件
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout PR Code
        uses: actions/checkout@v3
      
      # 假设置环境
      - name: Setup environment
        run: echo "Setting up environment"
      
      # 假构建
      - name: Build
        run: echo "Building project"
      
      # 假测试
      - name: Run tests
        run: echo "Running tests"
